# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdc5b4a42fb99e0512576b42d966905c46e5ed8a7d92ff5c0e85949a6404dad85182dad3b898a229cde532944c64d77499dc5b7fabe657a7475dcb41ffc63c75

test:
  secret_key_base: 94298d834745c9fe9a3870ce903c79a9be4ae1e729bcba60fa595e754e526d12f3457b424e92a53ec2644eba6174f24278e8459848f95c509b29fb967e589a9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
